from __future__ import annotations

from .models import EvidenceItem, EvidenceQuality, EvidenceType


def _item(
    id: str,
    category: EvidenceType,
    title: str,
    summary: str,
    source_name: str,
    source_url: str,
    quality: EvidenceQuality,
    independent_key: str,
    *,
    citation: str | None = None,
    stance: str = "supports",
    direction: str = "unresolved",
    directness: float = 0.7,
    excerpt: str | None = None,
) -> EvidenceItem:
    return EvidenceItem(
        id=id,
        category=category,
        title=title,
        summary=summary,
        source_name=source_name,
        source_url=source_url,
        quality=quality,
        independent_key=independent_key,
        citation=citation,
        stance=stance,
        direction=direction,
        directness=directness,
        excerpt=excerpt,
        raw_source="Curated demo fixture; verify against the linked source before scientific use.",
    )


DEMO_EVIDENCE: dict[tuple[str, str], list[EvidenceItem]] = {
    ("ATOPIC DERMATITIS", "IL4R"): [
        _item(
            "il4r-mr",
            EvidenceType.MENDELIAN_RANDOMIZATION,
            "Cis-pQTL Mendelian randomization supports causal IL4R effect on disease",
            "Instrumenting circulating IL-4Rα via cis-pQTLs yields a disease-direction consistent effect on atopic dermatitis risk, mirroring pharmacological blockade.",
            "Open Targets Genetics",
            "https://genetics.opentargets.org/study/GCST90014324",
            EvidenceQuality.HIGH,
            "il4r-cis-mr",
            direction="inhibit",
            directness=0.9,
        ),
        _item(
            "il4r-coloc",
            EvidenceType.COLOCALIZATION,
            "Skin eQTL colocalizes with atopic dermatitis GWAS signal at IL4R",
            "Colocalization (H4 posterior high) links the disease-associated locus to IL4R regulation in disease-relevant tissue, arguing against a bystander gene.",
            "Open Targets Genetics",
            "https://genetics.opentargets.org/gene/ENSG00000077238",
            EvidenceQuality.HIGH,
            "il4r-coloc",
            direction="inhibit",
            directness=0.88,
        ),
        _item(
            "il4r-genetics",
            EvidenceType.HUMAN_GENETICS,
            "Human genetic association supports the IL-4/IL-13 axis",
            "Disease-associated loci and target-level genetics provide human support for IL4R pathway involvement.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000077238/associations",
            EvidenceQuality.HIGH,
            "human-genetics-il4r",
            directness=0.86,
        ),
        _item(
            "il4r-perturb",
            EvidenceType.CAUSAL_PERTURBATION,
            "Blocking IL-4Rα suppresses type 2 inflammatory signaling",
            "Target perturbation blocks signaling from both IL-4 and IL-13, upstream of disease-associated transcriptional programs.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/29045222/",
            EvidenceQuality.HIGH,
            "il4r-blockade",
            citation="PMID: 29045222",
            direction="inhibit",
            directness=0.95,
        ),
        _item(
            "il4r-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Target-engaging therapy improves clinical disease",
            "Dupilumab blocks IL-4Rα and demonstrated efficacy in randomized atopic dermatitis trials.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/27690741/",
            EvidenceQuality.HIGH,
            "dupilumab-phase3",
            citation="PMID: 27690741",
            direction="inhibit",
            directness=1.0,
            excerpt="Two randomized, placebo-controlled phase 3 trials evaluated dupilumab in adults with atopic dermatitis.",
        ),
        _item(
            "il4r-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "Mechanism is coherent in disease-relevant tissue",
            "IL-4Rα integrates IL-4/IL-13 signaling that affects epidermal barrier and type 2 inflammation in skin.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-6785807",
            EvidenceQuality.HIGH,
            "il4r-pathway",
            direction="inhibit",
            directness=0.9,
        ),
        _item(
            "il4r-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "Disease-state expression is consistent but not causal alone",
            "Skin transcriptomic observations support pathway activity; this is treated as context, not proof.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000077238",
            EvidenceQuality.MODERATE,
            "il4r-expression",
            directness=0.65,
        ),
    ],
    ("ATOPIC DERMATITIS", "FLG"): [
        _item(
            "flg-genetics",
            EvidenceType.HUMAN_GENETICS,
            "Loss-of-function variants strongly increase disease risk",
            "FLG loss-of-function is a replicated human genetic risk factor for atopic dermatitis.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/16550169/",
            EvidenceQuality.HIGH,
            "flg-lof-genetics",
            citation="PMID: 16550169",
            direction="activate",
            directness=1.0,
        ),
        _item(
            "flg-mr-gap",
            EvidenceType.MENDELIAN_RANDOMIZATION,
            "No tractable Mendelian randomization instrument for filaggrin restoration",
            "The dominant FLG signal is loss-of-function; a positive-direction MR instrument for barrier-restoring intervention is not established.",
            "Open Targets Genetics",
            "https://genetics.opentargets.org/gene/ENSG00000143631",
            EvidenceQuality.MODERATE,
            "flg-mr-gap",
            stance="contradicts",
            direction="activate",
            directness=0.6,
        ),
        _item(
            "flg-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "Barrier biology is directly relevant to skin disease",
            "Filaggrin is central to epidermal differentiation and barrier integrity.",
            "UniProt",
            "https://www.uniprot.org/uniprotkb/P20930/entry",
            EvidenceQuality.HIGH,
            "flg-barrier",
            direction="activate",
            directness=0.95,
        ),
        _item(
            "flg-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "Reduced filaggrin is observed in lesional skin",
            "Expression is directionally coherent, but may also reflect inflammatory state.",
            "Europe PMC",
            "https://europepmc.org/article/MED/16550169",
            EvidenceQuality.MODERATE,
            "flg-expression",
            direction="activate",
            directness=0.65,
        ),
    ],
    ("ATOPIC DERMATITIS", "S100A8"): [
        _item(
            "s100a8-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "Strong inflammatory-state up-regulation",
            "S100A8 is elevated in inflamed tissue, establishing association with disease state but not causal direction.",
            "Europe PMC",
            "https://europepmc.org/search?query=S100A8%20atopic%20dermatitis",
            EvidenceQuality.HIGH,
            "s100a8-expression",
            directness=0.9,
        ),
        _item(
            "s100a8-literature",
            EvidenceType.LITERATURE,
            "Frequent disease co-mention",
            "The gene is repeatedly discussed as an inflammation marker; co-mention is low-tier evidence.",
            "Europe PMC",
            "https://europepmc.org/search?query=S100A8%20skin%20inflammation",
            EvidenceQuality.MODERATE,
            "s100a8-literature",
            directness=0.6,
        ),
        _item(
            "s100a8-perturb-counter",
            EvidenceType.CAUSAL_PERTURBATION,
            "No disease-relevant rescue evidence identified",
            "The curated search did not identify direct human skin perturbation evidence that normalizes disease phenotype.",
            "BioLead evidence gap",
            "https://europepmc.org/search?query=S100A8%20atopic%20dermatitis%20inhibition",
            EvidenceQuality.MODERATE,
            "s100a8-negative-search",
            stance="contradicts",
            direction="inhibit",
            directness=0.75,
        ),
        _item(
            "s100a8-genetics-counter",
            EvidenceType.HUMAN_GENETICS,
            "No direct causal human genetic assignment identified",
            "Disease-state expression is not accompanied by strong fine-mapped or colocalized causal-gene evidence in this fixture.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000143546/associations",
            EvidenceQuality.MODERATE,
            "s100a8-genetic-gap",
            stance="contradicts",
            directness=0.7,
        ),
    ],
    ("ATOPIC DERMATITIS", "IL13"): [
        _item(
            "il13-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "IL13-neutralizing antibody improves atopic dermatitis",
            "Tralokinumab binds IL13 and improves EASI and IGA in randomized atopic dermatitis trials, establishing target-engaging clinical rescue.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/33890792/",
            EvidenceQuality.HIGH,
            "il13-tralokinumab",
            citation="PMID: 33890792",
            direction="inhibit",
            directness=1.0,
        ),
        _item(
            "il13-lebrikizumab",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Lebrikizumab (anti-IL13) is efficacious in moderate-to-severe AD",
            "Phase 3 lebrikizumab trials show clinically meaningful skin clearance, independently replicating the IL13 blockade rescue signal.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/36912559/",
            EvidenceQuality.HIGH,
            "il13-lebrikizumab",
            citation="PMID: 36912559",
            direction="inhibit",
            directness=0.98,
        ),
        _item(
            "il13-genetics",
            EvidenceType.HUMAN_GENETICS,
            "IL13 locus is associated with atopic dermatitis risk",
            "Human genetic association at IL13 supports the ligand, not only the shared IL4R receptor, as a causal node in type 2 skin disease.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000169194/associations",
            EvidenceQuality.HIGH,
            "il13-gwas",
            direction="inhibit",
            directness=0.86,
        ),
        _item(
            "il13-perturb",
            EvidenceType.CAUSAL_PERTURBATION,
            "Blocking IL13 suppresses type 2 inflammatory signaling in skin",
            "Direct IL13 neutralization reduces STAT6-dependent transcription and epidermal barrier disruption in disease-relevant models.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/29045222/",
            EvidenceQuality.HIGH,
            "il13-blockade",
            citation="PMID: 29045222",
            direction="inhibit",
            directness=0.9,
        ),
        _item(
            "il13-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "IL13 is the dominant type 2 cytokine in chronic atopic skin",
            "IL13 signaling through IL4R/IL13RA1 is coherent with spongiosis, barrier failure, and itch in atopic dermatitis.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-6785807",
            EvidenceQuality.HIGH,
            "il13-pathway",
            direction="inhibit",
            directness=0.9,
        ),
    ],
    ("ATOPIC DERMATITIS", "JAK1"): [
        _item(
            "jak1-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Selective JAK1 inhibition improves atopic dermatitis",
            "Abrocitinib (JAK1) improved EASI-75 and itch in randomized JADE trials, a target-engaging clinical rescue of the JAK-STAT node downstream of IL4R/IL13.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/34023004/",
            EvidenceQuality.HIGH,
            "jak1-abrocitinib",
            citation="PMID: 34023004",
            direction="inhibit",
            directness=1.0,
        ),
        _item(
            "jak1-upadacitinib",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Upadacitinib (JAK1) replicates clinical rescue in AD",
            "Measure Up phase 3 trials show upadacitinib efficacy in moderate-to-severe atopic dermatitis, an independent JAK1 pharmacology pillar.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/34023003/",
            EvidenceQuality.HIGH,
            "jak1-upadacitinib",
            citation="PMID: 34023003",
            direction="inhibit",
            directness=0.96,
        ),
        _item(
            "jak1-perturb",
            EvidenceType.CAUSAL_PERTURBATION,
            "JAK1 blockade interrupts IL4/IL13 STAT6 signaling",
            "Pharmacologic JAK1 inhibition suppresses type 2 cytokine signaling that drives epidermal inflammation in atopic dermatitis.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/29045222/",
            EvidenceQuality.HIGH,
            "jak1-stat-block",
            citation="PMID: 29045222",
            direction="inhibit",
            directness=0.88,
        ),
        _item(
            "jak1-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "JAK1 is the kinase hub for IL4R type 2 signaling in skin",
            "IL4R/IL13RA1 signaling depends on JAK1; inhibiting JAK1 is mechanistically downstream of the IL4R driver axis.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-6785807",
            EvidenceQuality.HIGH,
            "jak1-pathway",
            direction="inhibit",
            directness=0.92,
        ),
        _item(
            "jak1-genetics",
            EvidenceType.HUMAN_GENETICS,
            "JAK-STAT pathway genetics supports atopic risk",
            "Pathway-level human genetics including JAK1 nodes is consistent with a causal inflammatory circuit in atopic dermatitis.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000162434/associations",
            EvidenceQuality.MODERATE,
            "jak1-ot",
            directness=0.72,
        ),
    ],
    ("ATOPIC DERMATITIS", "IL31RA"): [
        _item(
            "il31ra-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Nemolizumab (anti-IL31RA) improves AD itch and lesions",
            "IL31RA blockade with nemolizumab reduced pruritus and improved skin signs in randomized atopic dermatitis trials.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/35172084/",
            EvidenceQuality.HIGH,
            "il31ra-nemolizumab",
            citation="PMID: 35172084",
            direction="inhibit",
            directness=0.95,
        ),
        _item(
            "il31ra-perturb",
            EvidenceType.CAUSAL_PERTURBATION,
            "Blocking IL31RA interrupts itch-associated type 2 signaling",
            "IL31/IL31RA perturbation reduces neuronal and cutaneous inflammatory signaling linked to atopic itch.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/28181335/",
            EvidenceQuality.HIGH,
            "il31ra-blockade",
            citation="PMID: 28181335",
            direction="inhibit",
            directness=0.88,
        ),
        _item(
            "il31ra-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "IL31RA is the on-neuron/on-skin receptor for atopic itch",
            "IL31RA/OSMR is coherent with pruritus and barrier-adjacent inflammation in atopic dermatitis.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-6785807",
            EvidenceQuality.HIGH,
            "il31ra-pathway",
            direction="inhibit",
            directness=0.84,
        ),
        _item(
            "il31ra-genetics",
            EvidenceType.HUMAN_GENETICS,
            "IL31/IL31RA axis has human genetic and target support",
            "Target-level genetics and clinical pharmacology converge on IL31RA as a causal itch node rather than a bystander marker.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000115631/associations",
            EvidenceQuality.MODERATE,
            "il31ra-ot",
            directness=0.7,
        ),
    ],
    ("ATOPIC DERMATITIS", "S100A9"): [
        _item(
            "s100a9-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "S100A9 is strongly up-regulated in inflamed atopic skin",
            "S100A9 (calprotectin heterodimer with S100A8) tracks disease-state inflammation on tape-strip and lesional transcriptomes.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/29309794/",
            EvidenceQuality.HIGH,
            "s100a9-expression",
            citation="PMID: 29309794",
            directness=0.88,
        ),
        _item(
            "s100a9-literature",
            EvidenceType.LITERATURE,
            "S100A9 is discussed as an alarmin, not a proven driver",
            "Literature treats S100A9 as an inflammatory marker adjacent to S100A8; co-mention is not causal assignment.",
            "Europe PMC",
            "https://europepmc.org/search?query=S100A9%20atopic%20dermatitis",
            EvidenceQuality.MODERATE,
            "s100a9-literature",
            directness=0.58,
        ),
        _item(
            "s100a9-perturb-counter",
            EvidenceType.CAUSAL_PERTURBATION,
            "No S100A9-directed rescue evidence in human AD",
            "The curated search did not identify a target-engaging S100A9 intervention that reverses atopic dermatitis.",
            "Europe PMC",
            "https://europepmc.org/search?query=S100A9%20atopic%20dermatitis%20inhibition",
            EvidenceQuality.MODERATE,
            "s100a9-negative",
            stance="contradicts",
            direction="inhibit",
            directness=0.74,
        ),
        _item(
            "s100a9-genetics-counter",
            EvidenceType.HUMAN_GENETICS,
            "No strong causal gene assignment for S100A9 in AD",
            "Unlike IL4R/IL13, S100A9 lacks convergent MR/colocalization/clinical pillars in this dossier.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000163220/associations",
            EvidenceQuality.MODERATE,
            "s100a9-genetic-gap",
            stance="contradicts",
            directness=0.7,
        ),
    ],
    ("PSORIASIS", "IL17A"): [
        _item(
            "il17a-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Secukinumab (anti-IL17A) clears plaque psoriasis",
            "ERASURE and FIXTURE phase 3 trials showed IL17A blockade produces high PASI responses, a target-engaging clinical rescue.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/25007392/",
            EvidenceQuality.HIGH,
            "il17a-secukinumab",
            citation="PMID: 25007392",
            direction="inhibit",
            directness=1.0,
        ),
        _item(
            "il17a-ixekizumab",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Ixekizumab independently confirms IL17A as a psoriasis driver",
            "UNCOVER trials replicate clinical efficacy of IL17A neutralization, a second independent pharmacology pillar.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/26153825/",
            EvidenceQuality.HIGH,
            "il17a-ixekizumab",
            citation="PMID: 26153825",
            direction="inhibit",
            directness=0.98,
        ),
        _item(
            "il17a-genetics",
            EvidenceType.HUMAN_GENETICS,
            "IL17 pathway genetics supports psoriasis risk",
            "Human genetics around the IL23/IL17 axis, including IL17A-related loci, supports causal inflammatory circuitry in psoriasis.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000112115/associations",
            EvidenceQuality.HIGH,
            "il17a-gwas",
            direction="inhibit",
            directness=0.84,
        ),
        _item(
            "il17a-perturb",
            EvidenceType.CAUSAL_PERTURBATION,
            "IL17A neutralization suppresses psoriatic epidermal inflammation",
            "Direct IL17A blockade reduces keratinocyte inflammatory programs that define plaque psoriasis.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/25007392/",
            EvidenceQuality.HIGH,
            "il17a-blockade",
            citation="PMID: 25007392",
            direction="inhibit",
            directness=0.9,
        ),
        _item(
            "il17a-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "IL17A is the effector cytokine of the psoriatic IL23/Th17 axis",
            "IL17A signaling in keratinocytes is coherent with acanthosis, neutrophil recruitment, and plaque formation.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-448424",
            EvidenceQuality.HIGH,
            "il17a-pathway",
            direction="inhibit",
            directness=0.92,
        ),
    ],
    ("PSORIASIS", "IL23R"): [
        _item(
            "il23r-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "IL23 p19 blockade (guselkumab) improves plaque psoriasis",
            "VOYAGE trials show IL23 inhibition produces durable PASI responses, rescue evidence for the IL23R pathway.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/28514633/",
            EvidenceQuality.HIGH,
            "il23r-guselkumab",
            citation="PMID: 28514633",
            direction="inhibit",
            directness=0.96,
        ),
        _item(
            "il23r-risankizumab",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Risankizumab independently confirms IL23 pathway rescue",
            "UltIMMa-1/2 demonstrate IL23 p19 blockade efficacy, a second clinical pillar on the IL23R axis.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/31174904/",
            EvidenceQuality.HIGH,
            "il23r-risankizumab",
            citation="PMID: 31174904",
            direction="inhibit",
            directness=0.95,
        ),
        _item(
            "il23r-genetics",
            EvidenceType.HUMAN_GENETICS,
            "IL23R is a canonical psoriasis risk gene",
            "IL23R coding and regulatory variants are among the strongest replicated human genetic associations in psoriasis.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/18369459/",
            EvidenceQuality.HIGH,
            "il23r-gwas",
            citation="PMID: 18369459",
            direction="inhibit",
            directness=0.95,
        ),
        _item(
            "il23r-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "IL23R sustains pathogenic Th17 cells in psoriatic skin",
            "IL23R signaling maintains IL17-producing T cells; blocking the axis collapses the psoriasis effector program.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-9020956",
            EvidenceQuality.HIGH,
            "il23r-pathway",
            direction="inhibit",
            directness=0.9,
        ),
    ],
    ("PSORIASIS", "TYK2"): [
        _item(
            "tyk2-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Deucravacitinib (TYK2) is efficacious in plaque psoriasis",
            "POETYK PSO phase 3 trials show allosteric TYK2 inhibition improves PASI, a target-engaging clinical rescue.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/35320695/",
            EvidenceQuality.HIGH,
            "tyk2-deucravacitinib",
            citation="PMID: 35320695",
            direction="inhibit",
            directness=1.0,
        ),
        _item(
            "tyk2-genetics",
            EvidenceType.HUMAN_GENETICS,
            "TYK2 is a psoriasis GWAS gene with a protective loss-of-function allele",
            "Human genetics links TYK2 to psoriasis risk; a hypomorphic allele is protective, matching the pharmacology direction (inhibit).",
            "Open Targets Genetics",
            "https://genetics.opentargets.org/gene/ENSG00000105397",
            EvidenceQuality.HIGH,
            "tyk2-gwas",
            direction="inhibit",
            directness=0.92,
        ),
        _item(
            "tyk2-perturb",
            EvidenceType.CAUSAL_PERTURBATION,
            "TYK2 inhibition interrupts IL23/IL17 signaling",
            "Selective TYK2 blockade reduces IL23-dependent STAT signaling that drives psoriatic inflammation.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/35320695/",
            EvidenceQuality.HIGH,
            "tyk2-blockade",
            citation="PMID: 35320695",
            direction="inhibit",
            directness=0.88,
        ),
        _item(
            "tyk2-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "TYK2 is the JAK-family kinase for IL23R signaling",
            "IL23R pairs with TYK2; this is the closest JAK-family analogue of the IL4R–JAK1 node when the disease is switched to psoriasis.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-9020956",
            EvidenceQuality.HIGH,
            "tyk2-pathway",
            direction="inhibit",
            directness=0.9,
        ),
    ],
    ("PSORIASIS", "STAT3"): [
        _item(
            "stat3-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "STAT3 transduces IL23/IL6 signals in psoriatic keratinocytes and Th17 cells",
            "STAT3 is the transcription factor downstream of IL23R/TYK2; the mechanism is coherent but STAT3 itself is a hard drug target.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-9020956",
            EvidenceQuality.HIGH,
            "stat3-pathway",
            direction="inhibit",
            directness=0.8,
        ),
        _item(
            "stat3-genetics",
            EvidenceType.HUMAN_GENETICS,
            "STAT3 pathway genetics is associated with psoriasis",
            "STAT3 and upstream IL23/TYK2 genetics support the circuit, without uniquely assigning every GWAS signal to STAT3.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000168610/associations",
            EvidenceQuality.MODERATE,
            "stat3-ot",
            directness=0.7,
        ),
        _item(
            "stat3-clinical-gap",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "No approved STAT3-selective medicine in psoriasis",
            "Clinical rescue exists for IL17A, IL23, and TYK2, not for direct STAT3 targeting; BioLead therefore does not promote STAT3 to Driver.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/35320695/",
            EvidenceQuality.MODERATE,
            "stat3-no-drug",
            citation="PMID: 35320695",
            stance="contradicts",
            direction="inhibit",
            directness=0.72,
        ),
        _item(
            "stat3-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "pSTAT3 is elevated in psoriatic plaques",
            "Activation-state expression of STAT3 supports pathway activity and is treated as context, not causal proof.",
            "Europe PMC",
            "https://europepmc.org/search?query=STAT3%20psoriasis",
            EvidenceQuality.MODERATE,
            "stat3-expression",
            directness=0.62,
        ),
    ],
}


def get_demo_evidence(disease: str, gene: str) -> list[EvidenceItem]:
    key = (disease.strip().upper(), gene.strip().upper())
    return [item.model_copy(deep=True) for item in DEMO_EVIDENCE.get(key, [])]
