from __future__ import annotations

from .models import EvidenceItem, EvidenceQuality, EvidenceType


def _item(
    id: str,
    category: EvidenceType,
    title: str,
    summary: str,
    source_name: str,
    source_url: str,
    quality: EvidenceQuality,
    independent_key: str,
    *,
    citation: str | None = None,
    stance: str = "supports",
    direction: str = "unresolved",
    directness: float = 0.7,
    excerpt: str | None = None,
) -> EvidenceItem:
    return EvidenceItem(
        id=id,
        category=category,
        title=title,
        summary=summary,
        source_name=source_name,
        source_url=source_url,
        quality=quality,
        independent_key=independent_key,
        citation=citation,
        stance=stance,
        direction=direction,
        directness=directness,
        excerpt=excerpt,
        raw_source="Curated demo fixture; verify against the linked source before scientific use.",
    )


DEMO_EVIDENCE: dict[tuple[str, str], list[EvidenceItem]] = {
    ("ATOPIC DERMATITIS", "IL4R"): [
        _item(
            "il4r-mr",
            EvidenceType.MENDELIAN_RANDOMIZATION,
            "Cis-pQTL Mendelian randomization supports causal IL4R effect on disease",
            "Instrumenting circulating IL-4Rα via cis-pQTLs yields a disease-direction consistent effect on atopic dermatitis risk, mirroring pharmacological blockade.",
            "Open Targets Genetics",
            "https://genetics.opentargets.org/study/GCST90014324",
            EvidenceQuality.HIGH,
            "il4r-cis-mr",
            direction="inhibit",
            directness=0.9,
        ),
        _item(
            "il4r-coloc",
            EvidenceType.COLOCALIZATION,
            "Skin eQTL colocalizes with atopic dermatitis GWAS signal at IL4R",
            "Colocalization (H4 posterior high) links the disease-associated locus to IL4R regulation in disease-relevant tissue, arguing against a bystander gene.",
            "Open Targets Genetics",
            "https://genetics.opentargets.org/gene/ENSG00000077238",
            EvidenceQuality.HIGH,
            "il4r-coloc",
            direction="inhibit",
            directness=0.88,
        ),
        _item(
            "il4r-genetics",
            EvidenceType.HUMAN_GENETICS,
            "Human genetic association supports the IL-4/IL-13 axis",
            "Disease-associated loci and target-level genetics provide human support for IL4R pathway involvement.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000077238/associations",
            EvidenceQuality.HIGH,
            "human-genetics-il4r",
            directness=0.86,
        ),
        _item(
            "il4r-perturb",
            EvidenceType.CAUSAL_PERTURBATION,
            "Blocking IL-4Rα suppresses type 2 inflammatory signaling",
            "Target perturbation blocks signaling from both IL-4 and IL-13, upstream of disease-associated transcriptional programs.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/29045222/",
            EvidenceQuality.HIGH,
            "il4r-blockade",
            citation="PMID: 29045222",
            direction="inhibit",
            directness=0.95,
        ),
        _item(
            "il4r-clinical",
            EvidenceType.CLINICAL_PHARMACOLOGY,
            "Target-engaging therapy improves clinical disease",
            "Dupilumab blocks IL-4Rα and demonstrated efficacy in randomized atopic dermatitis trials.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/27690741/",
            EvidenceQuality.HIGH,
            "dupilumab-phase3",
            citation="PMID: 27690741",
            direction="inhibit",
            directness=1.0,
            excerpt="Two randomized, placebo-controlled phase 3 trials evaluated dupilumab in adults with atopic dermatitis.",
        ),
        _item(
            "il4r-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "Mechanism is coherent in disease-relevant tissue",
            "IL-4Rα integrates IL-4/IL-13 signaling that affects epidermal barrier and type 2 inflammation in skin.",
            "Reactome",
            "https://reactome.org/content/detail/R-HSA-6785807",
            EvidenceQuality.HIGH,
            "il4r-pathway",
            direction="inhibit",
            directness=0.9,
        ),
        _item(
            "il4r-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "Disease-state expression is consistent but not causal alone",
            "Skin transcriptomic observations support pathway activity; this is treated as context, not proof.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000077238",
            EvidenceQuality.MODERATE,
            "il4r-expression",
            directness=0.65,
        ),
    ],
    ("ATOPIC DERMATITIS", "FLG"): [
        _item(
            "flg-genetics",
            EvidenceType.HUMAN_GENETICS,
            "Loss-of-function variants strongly increase disease risk",
            "FLG loss-of-function is a replicated human genetic risk factor for atopic dermatitis.",
            "PubMed",
            "https://pubmed.ncbi.nlm.nih.gov/16550169/",
            EvidenceQuality.HIGH,
            "flg-lof-genetics",
            citation="PMID: 16550169",
            direction="activate",
            directness=1.0,
        ),
        _item(
            "flg-mr-gap",
            EvidenceType.MENDELIAN_RANDOMIZATION,
            "No tractable Mendelian randomization instrument for filaggrin restoration",
            "The dominant FLG signal is loss-of-function; a positive-direction MR instrument for barrier-restoring intervention is not established.",
            "Open Targets Genetics",
            "https://genetics.opentargets.org/gene/ENSG00000143631",
            EvidenceQuality.MODERATE,
            "flg-mr-gap",
            stance="contradicts",
            direction="activate",
            directness=0.6,
        ),
        _item(
            "flg-mechanism",
            EvidenceType.MECHANISTIC_COHERENCE,
            "Barrier biology is directly relevant to skin disease",
            "Filaggrin is central to epidermal differentiation and barrier integrity.",
            "UniProt",
            "https://www.uniprot.org/uniprotkb/P20930/entry",
            EvidenceQuality.HIGH,
            "flg-barrier",
            direction="activate",
            directness=0.95,
        ),
        _item(
            "flg-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "Reduced filaggrin is observed in lesional skin",
            "Expression is directionally coherent, but may also reflect inflammatory state.",
            "Europe PMC",
            "https://europepmc.org/article/MED/16550169",
            EvidenceQuality.MODERATE,
            "flg-expression",
            direction="activate",
            directness=0.65,
        ),
    ],
    ("ATOPIC DERMATITIS", "S100A8"): [
        _item(
            "s100a8-expression",
            EvidenceType.DIFFERENTIAL_EXPRESSION,
            "Strong inflammatory-state up-regulation",
            "S100A8 is elevated in inflamed tissue, establishing association with disease state but not causal direction.",
            "Europe PMC",
            "https://europepmc.org/search?query=S100A8%20atopic%20dermatitis",
            EvidenceQuality.HIGH,
            "s100a8-expression",
            directness=0.9,
        ),
        _item(
            "s100a8-literature",
            EvidenceType.LITERATURE,
            "Frequent disease co-mention",
            "The gene is repeatedly discussed as an inflammation marker; co-mention is low-tier evidence.",
            "Europe PMC",
            "https://europepmc.org/search?query=S100A8%20skin%20inflammation",
            EvidenceQuality.MODERATE,
            "s100a8-literature",
            directness=0.6,
        ),
        _item(
            "s100a8-perturb-counter",
            EvidenceType.CAUSAL_PERTURBATION,
            "No disease-relevant rescue evidence identified",
            "The curated search did not identify direct human skin perturbation evidence that normalizes disease phenotype.",
            "BioLead evidence gap",
            "https://europepmc.org/search?query=S100A8%20atopic%20dermatitis%20inhibition",
            EvidenceQuality.MODERATE,
            "s100a8-negative-search",
            stance="contradicts",
            direction="inhibit",
            directness=0.75,
        ),
        _item(
            "s100a8-genetics-counter",
            EvidenceType.HUMAN_GENETICS,
            "No direct causal human genetic assignment identified",
            "Disease-state expression is not accompanied by strong fine-mapped or colocalized causal-gene evidence in this fixture.",
            "Open Targets",
            "https://platform.opentargets.org/target/ENSG00000143546/associations",
            EvidenceQuality.MODERATE,
            "s100a8-genetic-gap",
            stance="contradicts",
            directness=0.7,
        ),
    ],
}


def get_demo_evidence(disease: str, gene: str) -> list[EvidenceItem]:
    key = (disease.strip().upper(), gene.strip().upper())
    return [item.model_copy(deep=True) for item in DEMO_EVIDENCE.get(key, [])]
